### ISSUE TITLE
support scientific colormaps

### ISSUE THREAD

**Issue by TomLav** [samhatfield/ncview-ncmaps#1]
I open a new issue here, to follow-up the discussion and developments that started from: https://github.com/TomLav/ncmaps/issues/8

In my last commit to ncview-ncmaps I brought a collection of .h files, but they do not seem to work, so have to continue debugging.

**Comment by TomLav** [comment]
Update : I did not break anything :-) next step is to have ncmaps to automatically generate file `src/colormaps_ncmaps.h`

**Comment by TomLav** [comment]
@samhatfield I guess I am done. Do you want to give it a try? We now have 69 scientific colormaps from matplotlib, cmocean, and cmcrameri (I did not import all from crameri).

**Comment by samhatfield** [comment]
Works fine for me! Nice one.

**Comment by TomLav** [comment]
Excellent. I think we could work further to de-activate (not remove) the legacy colormaps by default. Also we could work on the default ordering of the colormaps.
